### ISSUE TITLE
Add gradle cache support

### ISSUE THREAD

**Issue by rost5000** [rivancic/asyncapi-generator-gradle-plugin#18]
The gradle support cache mechanism, however, that plugin can not support caching. 

It is better to implement cache, by adding [annotation](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/CacheableTask.html). And also it is better to set output a task also cache. The example is [Gradle OpenApi generator](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt)

**Comment by rivancic** [comment]
Have to check it out.
Resource:
https://stackoverflow.com/questions/65101472/what-is-the-difference-between-from-cache-and-up-to-date-in-gradle

**Comment by rost5000** [comment]
Yes, it is probably `UP-TO-DATE`. I created this issue because It seemed to me that OpenaApi generator had a cacheable output because codegeneration is performing faster, however, it is just faster generator working..)
